package presentacion;

import bo.ChatBO;
import daoMock.UsuarioDAOMock;
import dto.UsuarioDTO;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.util.logging.Logger;

/**
 * Interfaz gráfica del cliente para la sala de chat.
 * @author Ixchel
 */
public class Pantalla_Cliente extends javax.swing.JFrame {
    private static final Logger logger = Logger.getLogger(Pantalla_Cliente.class.getName());
    private UsuarioDTO usuarioLogueado;
    private ChatBO chatBO;
    private UsuarioDAOMock usuarioDAO;
    
    /**
     * Inicializa los componentes, el estado visual del usuario y envía la 
     * notificación de conexión al servidor.
     */
    public Pantalla_Cliente(UsuarioDTO usuario, UsuarioDAOMock usuarioDAO) {
        initComponents();
        this.usuarioLogueado = usuario;
        this.usuarioDAO = usuarioDAO;
        this.chatBO = new ChatBO();
        jLabel2.setText("Estado: Conectado");
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Conectado al servidor: " + usuario.getNombre());
        jTextField2.setForeground(java.awt.Color.BLACK); 
        jTextField2.setText("");

        try {
            red.ConexionSocket conexion = red.ConexionSocket.getInstancia();
            dto.MensajeDTO mensajeRegistro = new dto.MensajeDTO(
                "Se ha unido al chat", 
                usuario, 
                java.time.LocalDateTime.now(), 
                dto.Tipo.PUBLICO
            );
            String jsonRegistro = mappers.MensajeMapper.toPythonJson(mensajeRegistro, "ALL") + "\n";
            conexion.enviarMensaje(jsonRegistro);
        } catch (Exception e) {
        }

        configurarHiloEscucha();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Volver");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente - Chat");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("CLIENTE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Estado: Conectado");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mensajes");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Escribe tu mensaje...");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Volver");
        jButton3.setActionCommand("Volver");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * Procesa y envía el mensaje escrito. Soporta el comando privado /priv.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String textoOriginal = jTextField2.getText().trim();
    
        if (textoOriginal.isEmpty() || textoOriginal.equals("Escribe tu mensaje...")) {
            return;
        }

        String destino = "ALL";
        String textoFiltrado = textoOriginal;
        dto.Tipo tipoMensaje = dto.Tipo.PUBLICO;

        if (textoOriginal.startsWith("/priv ")) {
            try {
                String[] partes = textoOriginal.split(" ", 3); 

                if (partes.length >= 3) {
                    destino = partes[1]; 
                    textoFiltrado = partes[2]; 
                    tipoMensaje = dto.Tipo.PRIVADO;
                } else {
                    JOptionPane.showMessageDialog(this, "Formato incorrecto. Usa: /priv NombreUsuario Mensaje", "Error de comando", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (Exception e) {
                System.err.println("Error procesando comando privado: " + e.getMessage());
            }
        }

        try {
            dto.MensajeDTO mensajeDto = new dto.MensajeDTO(
                textoFiltrado, 
                this.usuarioLogueado, 
                java.time.LocalDateTime.now(), 
                tipoMensaje
            );

            this.chatBO.procesarYEnviarMensaje(mensajeDto, destino);

            if (tipoMensaje == dto.Tipo.PRIVADO) {
                String horaActual = java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                jTextArea1.append("[" + horaActual + "] [Privado para " + destino + "]: " + textoFiltrado + "\n");
            }

            jTextField2.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al enviar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Limpia el marcador de posición (placeholder) del campo de texto al ganar el foco.
     */
    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if (jTextField2.getText().equals("Escribe tu mensaje...")) {
            jTextField2.setText("");
            jTextField2.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_jTextField2FocusGained

    /**
     * Cierra la ventana actual y regresa a la pantalla de Login.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Login(usuarioDAO).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Inicia el hilo en segundo plano para escuchar y procesar los mensajes 
     * entrantes del servidor en tiempo real.
     */
    private void configurarHiloEscucha() {
        Thread hilo = new Thread(() -> {
            red.ConexionSocket conexion = red.ConexionSocket.getInstancia();
            java.time.format.DateTimeFormatter formateadorCorto = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            try {
                while (true) {
                    String jsonRecibido = conexion.recibirMensaje();
                    
                    if (jsonRecibido == null) {
                        break; 
                    }
                    System.out.println("DEBUG CHAT - PROCESANDO: " + jsonRecibido);
                    try {
                        dto.MensajeDTO mensaje = mappers.MensajeMapper.toMensajeDTO(jsonRecibido);

                        if (mensaje != null) {
                            String emisor = mensaje.getEmisor().getNombre();
                            String contenido = mensaje.getContenido();
                            
                            String horaFechaFormateada = "";
                            if (mensaje.getFecha() != null) {
                                horaFechaFormateada = "[" + mensaje.getFecha().format(formateadorCorto) + "] ";
                            } else {
                                int indiceTimestamp = jsonRecibido.indexOf("\"timestamp\"");
                                if (indiceTimestamp != -1) {
                                    int inicioHora = jsonRecibido.indexOf(":", indiceTimestamp) + 14; 
                                    int finHora = inicioHora + 8;
                                    if (finHora <= jsonRecibido.length()) {
                                        horaFechaFormateada = "[" + jsonRecibido.substring(inicioHora, finHora) + "] ";
                                    }
                                }
                            }
                            
                            final String prefijoHora = horaFechaFormateada;
                            final String textoAImprimir;
                            
                            if (mensaje.getTipo() == dto.Tipo.PRIVADO) {
                                textoAImprimir = prefijoHora + "[Privado de " + emisor + "]: " + contenido + "\n";
                            } else {
                                textoAImprimir = prefijoHora + "[" + emisor + "]: " + contenido + "\n";
                            }
                            
                            javax.swing.SwingUtilities.invokeLater(() -> {
                                jTextArea1.append(textoAImprimir);
                            });
                        }
                    } catch (Exception mapperEx) {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jTextArea1.append("[Raw]: " + jsonRecibido + "\n");
                        });
                    }
                }
            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jTextArea1.append("Conexión perdida con el servidor.\n");
                });
            } finally {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jLabel2.setText("Estado: Desconectado");
                    jLabel2.setForeground(java.awt.Color.RED);
                    jTextField2.setEnabled(false);
                    jButton1.setEnabled(false);
                });
            }
        });
        hilo.setDaemon(true); 
        hilo.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
